### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by chrisheaththomas** [MrPowers/spark-style-guide#3]
> Singluar

**Comment by MrPowers** [comment]
@chrisheaththomas - can you please provide some more details?  Thanks!

**Comment by chrisheaththomas** [comment]
Just a typo in the guide. The word above is misspelled.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MrPowers** [comment]
Thanks, fixed this spelling error and a bunch of other spelling mistakes as well.
